version: '3.7'

services:
  web:
    build: ./financial_management
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./financial_management:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=spend_tracker
volumes:
  postgres_data: